export const NEWS_API_KEY = '46444d10a9d54a35b94bd39b23484150';
export const NEWS_API_BASE_URL = 'https://newsapi.org/v2';
export const SEARCH_TIME_INTERVAL = 6; // В днях
export const COUNT_ARTICLES = 20; 
export const STEP_SHOW = 3; 
export const NOT_FOUND_IMG = './img/search_back.png';
export const GITHUB_BASE_URL = 'https://api.github.com'; 
export const GITHUB_USERNAME = 'MaxSavostyanov'; 
export const GITHUB_REPO = 'NewsAnalyzer'; 
export const GITHUB_TOKEN = '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'; 
export const GITHUB_COUNT = '10'; 
